name: Hello, World!
description: Greet the world
author: GitHub Actions

inputs:
  who-to-greet:
    description: Who to greet in the log
    required: true
    default: 'World'
    type: string

outputs:
  time:
    description: The time we greeted you

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
